"""add consent fields to patients

Revision ID: 383c32d2e4e0
Revises: 40278ff938d0
Create Date: 2026-07-28 08:08:31.588733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383c32d2e4e0'
down_revision: Union[str, None] = '40278ff938d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added so this doesn't break on databases that already have patient rows —
    # existing patients are marked as consent not on record, since we can't retroactively know.
    op.add_column(
        "patients",
        sa.Column("consent_given", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("patients", sa.Column("consent_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'consent_at')
    op.drop_column('patients', 'consent_given')
    # ### end Alembic commands ###
