"""baseline: initial schema with auth

Revision ID: 40278ff938d0
Revises: 
Create Date: 2026-07-28 07:39:18.705129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40278ff938d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('via_category', sa.String(), nullable=False),
    sa.Column('subtype_label', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('case_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_factors_detail', sa.Text(), nullable=True),
    sa.Column('red_flag_symptoms', sa.Text(), nullable=True),
    sa.Column('informational_flags', sa.Text(), nullable=True),
    sa.Column('via_finding', sa.String(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_factors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('age_first_intercourse', sa.Integer(), nullable=True),
    sa.Column('residence_type', sa.String(), nullable=True),
    sa.Column('literate', sa.Boolean(), nullable=True),
    sa.Column('multiple_partners', sa.Boolean(), nullable=True),
    sa.Column('discharge', sa.Boolean(), nullable=True),
    sa.Column('post_coital_bleeding', sa.Boolean(), nullable=True),
    sa.Column('parity', sa.Integer(), nullable=True),
    sa.Column('hiv_positive', sa.Boolean(), nullable=True),
    sa.Column('ocp_years', sa.Integer(), nullable=True),
    sa.Column('smoking_tobacco', sa.Boolean(), nullable=True),
    sa.Column('immunocompromised_or_std', sa.Boolean(), nullable=True),
    sa.Column('hpv_vaccinated', sa.Boolean(), nullable=True),
    sa.Column('family_history_cancer', sa.Boolean(), nullable=True),
    sa.Column('last_screening_date', sa.String(), nullable=True),
    sa.Column('last_screening_result', sa.String(), nullable=True),
    sa.Column('abnormal_bleeding_pattern', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_factors')
    op.drop_table('patient_images')
    op.drop_table('case_reviews')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('reference_images')
    op.drop_table('patients')
    # ### end Alembic commands ###
